name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: upgrade pip
        run: python -m pip install --upgrade pip 

      - name: virtualenv
        run: python -m venv venv

      - name: Install dependencies
        run: source venv/bin/activate && pip install -r requirements.txt
         
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

        
